goal_reached:
  reward: 15

ped_safe_distance:
  reward: -0.25
  safe_dist: 1.0

obs_safe_distance:
  reward: -0.15
  safe_dist: 0.4

collision:
  reward: -20

approach_goal:
  pos_factor: 0.5
  neg_factor: 0.6
  _on_safe_dist_violation: true

reverse_drive:
  reward: -0.05
  threshold: -0.3
  _on_safe_dist_violation: true

approach_globalplan:
  pos_factor: 0.1
  neg_factor: 0.15
  _on_safe_dist_violation: true

two_factor_velocity_difference:
  alpha: 0.005
  beta: 0.005
  _on_safe_dist_violation: true

# active_heading_direction:
#   r_angle: 0.6
#   _on_safe_dist_violation: true

max_steps_exceeded:
  reward: -10
